# -*- coding: utf-8 -*-
"""project_with_depol_noise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1lIKZcUqGCmIsERJLXH6cZRXRj92kKl
"""
import argparse

import qiskit
print("Using Qiskit version", qiskit.__version__)
from qiskit.circuit.library.n_local import n_local
from qiskit import QuantumCircuit
from qiskit.primitives import StatevectorSampler as Sampler
from qiskit.quantum_info import SparsePauliOp

import qiskit_aer
print("Using QiskitAer version", qiskit_aer.__version__)
from qiskit_aer.primitives import Estimator as Estimator

import pylatexenc

# for SciPy minimizer
from scipy.optimize import minimize
import numpy as np
import time
from numpy.linalg import eigvalsh

# for writing data into a CSV
import pandas as pd

"""Arguments:"""

parser = argparse.ArgumentParser()
parser.add_argument(
    "-n",
    "--niter",
    required=False,
    help="Number of iterations to collect and average (per error value)"
)
parser.add_argument(
    "-e",
    "--errs", 
    nargs='+', 
    type=float, 
    required=True,
    help="A list of errors for single-qubit gates (space-separated)"
)
parser.add_argument(
    "-f",
    "--filename",
    type=str,
    required=False,
    help="Name to attach to relevant files"
)
parser.add_argument(
    "-o",
    "--observable",
    type=int,
    required=True,
    help="Select observable (1, 2, or 3)"
)

args = parser.parse_args()
if args.niter == None:  niter = 10
else:                   niter = int(args.niter)
print(f"Simulating with {niter} iterations per error value")

errs = args.errs
# if niter == 1:
#     # we want to plot the energy
#     assert len(errs) == 1
#     cost_data = np.empty(0)
# else:
#     cost_data = np.array(['no'])

"""Define cost function:"""
def cost_func_vqe(params, ansatz, hamiltonian, estimator, cost_list=None):
        """Return estimate of energy from estimator

        Parameters:
            params (ndarray): Array of ansatz parameters
            ansatz (QuantumCircuit): Parameterized ansatz circuit
            hamiltonian (SparsePauliOp): Operator representation of Hamiltonian
            estimator (Estimator): Estimator primitive instance

        Returns:
            float: Energy estimate
        """
        # # Old:
        # pub = (ansatz, hamiltonian, params)
        # cost = estimator.run([pub]).result()[0].data.evs

        # New for Aer Estimator:
        cost = estimator.run(circuits=[ansatz], observables=[hamiltonian], parameter_values=[params]).result().values[0]

        if cost_list is not None:
            cost_list.append(cost)
        # if not (cost_data.shape[0] == 1 and cost_data[0] == 'no'):
        #     # we want to plot the energy
        #     print(f"appending " + str(cost) + " to " + str(cost_data))
        #     print(np.append(cost_data, [cost]))
        #     cost_data = np.append(cost_data, [cost]) 
        #     # !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! not working for some reason
             
        return cost

"""Set up observables"""
observables = [None,
               SparsePauliOp.from_list([("II", 2), ("XX", -2), ("YY", 3), ("ZZ", -3)]),
               SparsePauliOp.from_list([("XX", -1), ("YY", -1)]),
               SparsePauliOp.from_list([("ZZ", -1)])]
observable = observables[args.observable]


"""Create array for output:"""
headers = ['err_per_1q_gate', 'mean_normalized_err', 'std_normalized_err', 'mean_duration']
j_err_per_1q_gate = 0
j_mean_normalized_err = 1
j_std_normalized_err = 2
j_mean_duration = 3

data_shape = (len(errs), 4)
data = np.empty(data_shape)

if niter == 1:
    # want to record costs
    # columns are error values
    cost_table = [None for err_val in errs]
    

"""Loop through input errors and perform noisy simulation:"""
for i,err in enumerate(errs):
    data[i, j_err_per_1q_gate] = err

    """First, set up the noisy simulation:"""

    # build basis and per-gate error
    basis_gates = ['x', 'sx', 'rz', 'cx']
    # basis_gates = ['x', 'sx', 'cx']
    err_per_gate_1q = err
    err_per_gate_2q = 2 * err # (assuming 2q gates have 2x the error)
    # err_per_gate_2q = err # (assuming 2q gates have 2x the error)

    # if special input err=1, set errors to max
    if err == 1:
         print("(Using max error)")
         err_per_gate_1q = 0.99
         err_per_gate_2q = 0.99

    depol_err_1q = qiskit_aer.noise.depolarizing_error(err_per_gate_1q, 1)
    depol_err_2q = qiskit_aer.noise.depolarizing_error(err_per_gate_2q, 2)

    # build noise model --> noisy simulator
    noise_model = qiskit_aer.noise.NoiseModel()

    noise_model.add_all_qubit_quantum_error(depol_err_1q, instructions=['x', 'sx', 'rz'])
    # noise_model.add_all_qubit_quantum_error(depol_err_1q, instructions=['x', 'sx'])
    noise_model.add_all_qubit_quantum_error(depol_err_2q, instructions=['cx'])

    noisy_sim = qiskit_aer.AerSimulator(method='density_matrix', noise_model=noise_model)

    reference_circuit = QuantumCircuit(2)
    # reference_circuit.x(0)

    variational_form = n_local(
        num_qubits=2,
        rotation_blocks=["rz", "ry"],
        entanglement_blocks="cx",
        entanglement="linear",
        reps=1,
    )

    raw_ansatz = reference_circuit.compose(variational_form)
    # raw_ansatz.decompose().draw("mpl")
    transpiled_ansatz = qiskit.transpile(raw_ansatz, basis_gates=basis_gates)

    # noisy_estimator = Estimator(backend_options={'method': 'density_matrix',
    #                                              'noise_model': noise_model,
    #                                              'basis_gates': basis_gates})
    noisy_estimator = Estimator(backend_options={'method': 'density_matrix',
                                                 'noise_model': noise_model,
                                                 'basis_gates': basis_gates},
                                run_options={'shots': 100})
    sampler = Sampler()

    # initial parameters
    x0 = np.ones(raw_ansatz.num_parameters)
    # x0 = np.random.uniform(0, 2*np.pi, raw_ansatz.num_parameters)

    """Now compute optimal parameters. The minimization line is essentially where the "run" is happening.
    We repeat that line several times to collect several data points for the final normalized error."""

    print(f"Performing simulation for error={err}")

    # mathematical solution
    eigenvalues = eigvalsh(observable.to_matrix())

    durations    = np.empty((niter,))
    normalized_errs = np.empty((niter,))
    if niter > 1:
        for j in range(niter):
            start_time = time.time()  # START
            result = minimize(
                cost_func_vqe,
                x0,
                args=(transpiled_ansatz, observable, noisy_estimator),
                method="COBYLA",
                options={"maxiter": 500, "disp": False},
            )
            # print(result.fun)
            # print(min(eigenvalues))
            end_time = time.time()    # END

            durations[j] = end_time - start_time
            normalized_errs[j] = abs((result.fun - min(eigenvalues))/(max(eigenvalues) - min(eigenvalues)))
    else:
        print("Recording costs...")
        # niter is 1, want to record costs
        cost_list = []
        start_time = time.time()  # START
        result = minimize(
            cost_func_vqe,
            x0,
            args=(transpiled_ansatz, observable, noisy_estimator, cost_list),
            method="COBYLA",
            options={"maxiter": 500, "disp": False},
        )
        # print(result.fun)
        # print(min(eigenvalues))
        end_time = time.time()    # END

        durations[0] = end_time - start_time
        normalized_errs[0] = abs((result.fun - min(eigenvalues))/(max(eigenvalues) - min(eigenvalues)))

        cost_table[i] = cost_list
    
    mean_normalized_err = np.mean(normalized_errs)
    std_normalized_err = np.std(normalized_errs)
    mean_duration = np.mean(durations)

    data[i, j_mean_normalized_err] = mean_normalized_err
    data[i, j_std_normalized_err] = std_normalized_err
    data[i, j_mean_duration] = mean_duration
    print("..........MEAN NORM ERR:", mean_normalized_err)
    print("...........MAX NORM ERR:", np.max(normalized_errs))
    print("...........STD NORM ERR:", std_normalized_err)
    print("..........MEAN DURATION:", mean_duration)

"""Set up data file:"""
filename = args.filename
if filename is not None:
    df = pd.DataFrame(data, columns=headers)
    df.to_csv(filename + f'_n{niter}.csv')

# if filename is not None and niter == 1:
#     # Create a dictionary where keys are error rates and values are the cost lists
#     # This handles different lengths automatically by padding with NaN at the end
#     data_dict = {str(err_val): cost_table[i] for i, err_val in enumerate(errs)}
#     cost_df = pd.DataFrame(data_dict)
    
#     cost_df.to_csv(filename + f'_costs.csv', index=False)

if filename is not None and niter == 1:
    max_col_len = max([len(col) for col in cost_table])

    full_cost_table = [[None for i in range(len(errs))] for k in range(max_col_len)]

    for i,col in enumerate(cost_table):
        for k,val in enumerate(col):
            full_cost_table[k][i] = val

    cost_df = pd.DataFrame(full_cost_table, columns=[str(err_val) for err_val in errs])
    cost_df.to_csv(filename + f'_costs.csv', index=False)

# if filename != None and niter == 1:
#     print(cost_data) # <------ empty for some reason
#     cost_df = pd.DataFrame(cost_data, columns=['cost'])
#     cost_df.to_csv(filename + f'_costs.csv')
    

# END OF CURRENT CODE #
#######################







# # SciPy minimizer routine
# from scipy.optimize import minimize
# import time

# start_time = time.time()

# result = minimize(
#     cost_func_vqe,
#     x0,
#     args=(raw_ansatz, observable_1, noisy_estimator),
#     method="COBYLA",
#     options={"maxiter": 1000, "disp": True},
# )

# end_time = time.time()
# execution_time = end_time - start_time

# result

"""Now check against NumPy's linear algrebra eigensolver. (This is possible because we are only using two qubits.)"""

# from numpy.linalg import eigvalsh

# solution_eigenvalue = min(eigvalsh(observable_1.to_matrix()))

# print(f"""Number of iterations: {result.nfev}""")
# print(f"""Time (s): {execution_time}""")

# print(
#     f"Percent error: {100*abs((result.fun - solution_eigenvalue)/solution_eigenvalue):.2e}"
# )
